travis:
  secure:
    BINSTAR_TOKEN: JiOq54MNMwq/lF5P21gioHE17KlqFm34XbsSdjdSwCGcIJIdAO81LQnUN3+0/k36OAKANGOBNCjIhsiRZGhDOPzJz1dAOQHPaUKZPUPdRB0MkWLu0HdgAUKx65WZz27f76OowuHwaVIJ37/cqRDMBeJkVelI+hWwdo1pvCr0ect+TWQSfAMinNmE1w1LgnYjIRk+nLkMboSTcipfF9+BL1IhwqwwzQtdiHjk1v2yDnwnE4Mp68MH/cdzoT1mucGEoH8slWUjg54yKRbZdqqD7Y9/O89S1Mk3QeCB3QoX2xT10R/g5M5cWBuDEtbM5G2yf6xnIZXt+/XUATy3lpZsHB7Q9q/kVZwLAvs0f9fNbpMUm5CX5hsXJkaBNrhxxNBWbLEatvdCFXysqeKINvKsbWT3189PfHvQnWckZOlRKVxAd9vAc+58HBrNVEoE9yifGfmkjxA+NM4lL6QNQQ/OaZmtI9wm2ZsSWvQ25pMm+hUpkdT686YYqQN/cweD62st1jQOc9gavXDTlnGTEnBbaN5ighM+NV2kInnhW4YfKjGNtXD7ARKvkeDkKgGJcOIuZOE9v1D2UJ6DQhRHpPYSnAVrhRx81B6Oy2oHXgVPRK1uM8g12mAwfZXnMvGx7wALiw7ETIFb6vcRLEFUIZecJSLIzUxBYZGgMtSUlssKS/A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
