travis:
  secure:
    BINSTAR_TOKEN: fU7y+XHd8Fvgay1WBDm/k7+R83mk8jAIGk7Qw4+QUldHJ5tLXgQdjJkoiVrDi5zUAHVbNnWJekDDrTMbhyJK6+0wPEoNhIRs61o/RfXq54S+pb0tw+VBdDmV4K/B5qlpg+8FMP7DxGYEa86FoupjRofWZNJlX8WnSBcKDnJkb5qHGgvfViCX2kvFONAuUpIFgd1HrCPCaNjvlIqAq5j0/gpcNIE74+x+pvVyV2RaQE3XyRAYr+KKSzsETHNUsQqWNvjyaKPdH6YBhHuXT9Va7dp+B6M9JXIFMs6HrFLET2b0uy8gnvxvKqwx6XeQN4dWoi9u/GJHXx6YqIogVZ2nmmEMvxsLJFsyiTK40jJY4Ia0NriQeP85ohcT6e/Ty6na+ukVlNO5yfR+cm8HROocNHrNiVuOwSjKZyv8k8weyj47smSaHaftjX8E6rTxS0TKAMHE7El1Fqz/zenu6xig6Neen5AfyVIpVDtUl2TWe2o/6E7Qiy7rSRZbIQIdQe65oL83Sm2bqTDKE916XWy+PYuVnd2lu+SiZ7CmZ5t8tTsrP5gM7aV/T2qHEvMfoTJVpyS0Rlte7vSgd0Qhdd+TJhahJyOr7Dlv5+J26ny0OcRJFrgDdIm3Gbtm8t+Rs7ytYVYhoNiU5a3MGNKQTeDm9QbNbi4tHoJOqfZl18eX+Tg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
